### ISSUE TITLE
while opening ./main.py

### ISSUE THREAD

**Issue by cyberengulf** [gotr00t0day/IGF#1]
Traceback (most recent call last):
  File "/home/kali/Desktop/Framework/IGF/./main.py", line 3, in <module>
    import igf
  File "/home/kali/Desktop/Framework/IGF/igf.py", line 14, in <module>
    from pygeocoder import Geocoder
  File "/home/kali/.local/lib/python3.10/site-packages/pygeocoder.py", line 28, in <module>
    from pygeolib import GeocoderError, GeocoderResult
  File "/home/kali/.local/lib/python3.10/site-packages/pygeolib.py", line 5, in <module>
    class GeocoderResult(collections.Iterator):
AttributeError: module 'collections' has no attribute 'Iterator'

**Comment by IllusionAC** [comment]
change collections.Iterator to collections.abc.Iterable in the file pygeolib.py located in your /home/kali/.local/lib/python3.10/site-packages/
use gedit or nano or whatever
for some people that file is located in /usr/local/lib/python3.10/dist-packages/
