### ISSUE TITLE
Cannot run ./main.py

### ISSUE THREAD

**Issue by d4rkhub** [gotr00t0day/IGF#5]
Show error No Module names colorama, even though colorama is already installed

username@Host-MacBook-Pro igf % ./main.py
Traceback (most recent call last):
  File "/Users/username/tools/IGF/./main.py", line 3, in <module>
    import igf
  File "/Users/username/tools/IGF/igf.py", line 3, in <module>
    from colorama import Fore, Back, Style
ModuleNotFoundError: No module named 'colorama'

**Comment by gotr00t0day** [comment]
Maybe run the pip3 install -r requirements.txt again or python3 main.py

**Comment by d4rkhub** [comment]
Problem solved after install manually pip3 sources.. thx

**Comment by Ravikm941** [comment]
Show error and unable to install pygeocoder

Traceback (most recent call last):
  File "/home/rat/Desktop/Software/IGF/main.py", line 3, in <module>
    import igf
  File "/home/rat/Desktop/Software/IGF/igf.py", line 13, in <module>
    from pygeocoder import Geocoder
ModuleNotFoundError: No module named 'pygeocoder'

**Comment by gotr00t0day** [comment]
> Show error and unable to install pygeocoder
> 
> Traceback (most recent call last): File "/home/rat/Desktop/Software/IGF/main.py", line 3, in import igf File "/home/rat/Desktop/Software/IGF/igf.py", line 13, in from pygeocoder import Geocoder ModuleNotFoundError: No module named 'pygeocoder'

did you run pip3 install -r requirements.txt ?
